name: Deploy to Pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy Web
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.4.0
        with:
          flutter-version: '2.12.x'
          channel: 'any'
      - run: |
        flutter build web --base-href="/blocks/"
        cd build/web
        git init
        git config user.name github-actions
        git config user.email github-actions@github.com
        git status
        git remote add origin https://${{secrets.commit_secret}}@github.com/satanic-santa/blocks.git
        git checkout -b gh-pages
        git add --all
        git commit -m "update"
        git push origin gh-pages -f